version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:5000
    depends_on:
      - api
    restart: unless-stopped

  # Remove Redis if not needed
  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped

# Remove the network definition to use the default